/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: comm.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "comm.pb-c.h"
void   fberhome__im_pbmp__init
                     (Fberhome__ImPbmp         *message)
{
  static Fberhome__ImPbmp init_value = FBERHOME__IM_PBMP__INIT;
  *message = init_value;
}
size_t fberhome__im_pbmp__get_packed_size
                     (const Fberhome__ImPbmp *message)
{
  assert(message->base.descriptor == &fberhome__im_pbmp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t fberhome__im_pbmp__pack
                     (const Fberhome__ImPbmp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &fberhome__im_pbmp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t fberhome__im_pbmp__pack_to_buffer
                     (const Fberhome__ImPbmp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &fberhome__im_pbmp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Fberhome__ImPbmp *
       fberhome__im_pbmp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Fberhome__ImPbmp *)
     protobuf_c_message_unpack (&fberhome__im_pbmp__descriptor,
                                allocator, len, data);
}
void   fberhome__im_pbmp__free_unpacked
                     (Fberhome__ImPbmp *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &fberhome__im_pbmp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   fberhome__fb_init_req__init
                     (Fberhome__FbInitReq         *message)
{
  static Fberhome__FbInitReq init_value = FBERHOME__FB_INIT_REQ__INIT;
  *message = init_value;
}
size_t fberhome__fb_init_req__get_packed_size
                     (const Fberhome__FbInitReq *message)
{
  assert(message->base.descriptor == &fberhome__fb_init_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t fberhome__fb_init_req__pack
                     (const Fberhome__FbInitReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &fberhome__fb_init_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t fberhome__fb_init_req__pack_to_buffer
                     (const Fberhome__FbInitReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &fberhome__fb_init_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Fberhome__FbInitReq *
       fberhome__fb_init_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Fberhome__FbInitReq *)
     protobuf_c_message_unpack (&fberhome__fb_init_req__descriptor,
                                allocator, len, data);
}
void   fberhome__fb_init_req__free_unpacked
                     (Fberhome__FbInitReq *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &fberhome__fb_init_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   fberhome__im_dbg_req__init
                     (Fberhome__ImDbgReq         *message)
{
  static Fberhome__ImDbgReq init_value = FBERHOME__IM_DBG_REQ__INIT;
  *message = init_value;
}
size_t fberhome__im_dbg_req__get_packed_size
                     (const Fberhome__ImDbgReq *message)
{
  assert(message->base.descriptor == &fberhome__im_dbg_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t fberhome__im_dbg_req__pack
                     (const Fberhome__ImDbgReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &fberhome__im_dbg_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t fberhome__im_dbg_req__pack_to_buffer
                     (const Fberhome__ImDbgReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &fberhome__im_dbg_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Fberhome__ImDbgReq *
       fberhome__im_dbg_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Fberhome__ImDbgReq *)
     protobuf_c_message_unpack (&fberhome__im_dbg_req__descriptor,
                                allocator, len, data);
}
void   fberhome__im_dbg_req__free_unpacked
                     (Fberhome__ImDbgReq *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &fberhome__im_dbg_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor fberhome__im_pbmp__field_descriptors[1] =
{
  {
    "pbmp",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Fberhome__ImPbmp, n_pbmp),
    offsetof(Fberhome__ImPbmp, pbmp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned fberhome__im_pbmp__field_indices_by_name[] = {
  0,   /* field[0] = pbmp */
};
static const ProtobufCIntRange fberhome__im_pbmp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor fberhome__im_pbmp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Fberhome.ImPbmp",
  "ImPbmp",
  "Fberhome__ImPbmp",
  "Fberhome",
  sizeof(Fberhome__ImPbmp),
  1,
  fberhome__im_pbmp__field_descriptors,
  fberhome__im_pbmp__field_indices_by_name,
  1,  fberhome__im_pbmp__number_ranges,
  (ProtobufCMessageInit) fberhome__im_pbmp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor fberhome__fb_init_req__field_descriptors[1] =
{
  {
    "unit",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Fberhome__FbInitReq, unit),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned fberhome__fb_init_req__field_indices_by_name[] = {
  0,   /* field[0] = unit */
};
static const ProtobufCIntRange fberhome__fb_init_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor fberhome__fb_init_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Fberhome.FbInitReq",
  "FbInitReq",
  "Fberhome__FbInitReq",
  "Fberhome",
  sizeof(Fberhome__FbInitReq),
  1,
  fberhome__fb_init_req__field_descriptors,
  fberhome__fb_init_req__field_indices_by_name,
  1,  fberhome__fb_init_req__number_ranges,
  (ProtobufCMessageInit) fberhome__fb_init_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor fberhome__im_dbg_req__field_descriptors[1] =
{
  {
    "enable",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Fberhome__ImDbgReq, enable),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned fberhome__im_dbg_req__field_indices_by_name[] = {
  0,   /* field[0] = enable */
};
static const ProtobufCIntRange fberhome__im_dbg_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor fberhome__im_dbg_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Fberhome.ImDbgReq",
  "ImDbgReq",
  "Fberhome__ImDbgReq",
  "Fberhome",
  sizeof(Fberhome__ImDbgReq),
  1,
  fberhome__im_dbg_req__field_descriptors,
  fberhome__im_dbg_req__field_indices_by_name,
  1,  fberhome__im_dbg_req__number_ranges,
  (ProtobufCMessageInit) fberhome__im_dbg_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
