/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: init.proto */

#ifndef PROTOBUF_C_init_2eproto__INCLUDED
#define PROTOBUF_C_init_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "comm.pb-c.h"

typedef struct _Fberhome__TestReq Fberhome__TestReq;
typedef struct _Fberhome__ImVerReq Fberhome__ImVerReq;


/* --- enums --- */


/* --- messages --- */

struct  _Fberhome__TestReq
{
  ProtobufCMessage base;
  Fberhome__ImPbmp *fe;
};
#define FBERHOME__TEST_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&fberhome__test_req__descriptor) \
    , NULL }


struct  _Fberhome__ImVerReq
{
  ProtobufCMessage base;
  char *build_release;
  char *build_user;
  char *build_host;
  char *build_date;
  char *build_arch;
};
#define FBERHOME__IM_VER_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&fberhome__im_ver_req__descriptor) \
    , NULL, NULL, NULL, NULL, NULL }


/* Fberhome__TestReq methods */
void   fberhome__test_req__init
                     (Fberhome__TestReq         *message);
size_t fberhome__test_req__get_packed_size
                     (const Fberhome__TestReq   *message);
size_t fberhome__test_req__pack
                     (const Fberhome__TestReq   *message,
                      uint8_t             *out);
size_t fberhome__test_req__pack_to_buffer
                     (const Fberhome__TestReq   *message,
                      ProtobufCBuffer     *buffer);
Fberhome__TestReq *
       fberhome__test_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   fberhome__test_req__free_unpacked
                     (Fberhome__TestReq *message,
                      ProtobufCAllocator *allocator);
/* Fberhome__ImVerReq methods */
void   fberhome__im_ver_req__init
                     (Fberhome__ImVerReq         *message);
size_t fberhome__im_ver_req__get_packed_size
                     (const Fberhome__ImVerReq   *message);
size_t fberhome__im_ver_req__pack
                     (const Fberhome__ImVerReq   *message,
                      uint8_t             *out);
size_t fberhome__im_ver_req__pack_to_buffer
                     (const Fberhome__ImVerReq   *message,
                      ProtobufCBuffer     *buffer);
Fberhome__ImVerReq *
       fberhome__im_ver_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   fberhome__im_ver_req__free_unpacked
                     (Fberhome__ImVerReq *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Fberhome__TestReq_Closure)
                 (const Fberhome__TestReq *message,
                  void *closure_data);
typedef void (*Fberhome__ImVerReq_Closure)
                 (const Fberhome__ImVerReq *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor fberhome__test_req__descriptor;
extern const ProtobufCMessageDescriptor fberhome__im_ver_req__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_init_2eproto__INCLUDED */
